### ISSUE TITLE
Search for post field doesn't yield any results

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#292]
**Describe the bug**
Currently I am unable to search for any posts using the search field. This makes it impossible for me to find posts.

**To Reproduce**
1. Go to DevHub's homepage
2. Type any key word in the "Search Posts" field
3. See hovering circle inside the search posts (e.g. loading button) without any search outputs

**Expected behavior**
I should see the posts that contain the search term/

**Screenshots**
![Screenshot 2023-10-10 at 4 22 14 PM](https://github.com/near/neardevhub-widgets/assets/110252255/f7d38e3f-44f9-4e42-92c6-f2c588f37027)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: Latest

**Comment by petersalomonsen** [comment]
The error is because of calling the contract method `get_posts` fails like this:

```
NEAR_ENV=mainnet near view devgovgigs.near get_posts '{}' 
View call: devgovgigs.near.get_posts({})
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: HostError(GuestPanic { panic_msg: "Cannot deserialize element" }).
{
  "block_hash": "8iGTZLLcTcWB6BhrVhdMZGNXScnJMdYraRdHN3ZuXcy3",
  "block_height": 103304522,
  "error": "wasm execution failed with error: HostError(GuestPanic { panic_msg: \"Cannot deserialize element\" })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: HostError(GuestPanic { panic_msg: "Cannot deserialize element" }).
{
  "block_hash": "8iGTZLLcTcWB6BhrVhdMZGNXScnJMdYraRdHN3ZuXcy3",
  "block_height": 103304522,
  "error": "wasm execution failed with error: HostError(GuestPanic { panic_msg: \"Cannot deserialize element\" })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

And it is because of particular posts like no 146:

```
NEAR_ENV=mainnet near view devgovgigs.near get_post '{"post_id": 146}'              
View call: devgovgigs.near.get_post({"post_id": 146})
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: HostError(GuestPanic { panic_msg: "Cannot deserialize element" }).
{
  "block_hash": "2dkpWC71CwFbw8uZiDES2SVDVprMYBgRTsBkAYEzA8Qv",
  "block_height": 103305310,
  "error": "wasm execution failed with error: HostError(GuestPanic { panic_msg: \"Cannot deserialize element\" })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: HostError(GuestPanic { panic_msg: "Cannot deserialize element" }).
{
  "block_hash": "2dkpWC71CwFbw8uZiDES2SVDVprMYBgRTsBkAYEzA8Qv",
  "block_height": 103305310,
  "error": "wasm execution failed with error: HostError(GuestPanic { panic_msg: \"Cannot deserialize element\" })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

While post no `145` works fine.

Need to find a way to reproduce the state of post 146, or a similar state in a test environment.
